import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import type { AssetInfo, InventoryReport, PaletteColor, ProcessResult, QueueStatus, Settings } from "./types";
import logoUrl from "../logo_Ui.png";
import "./styles.css";
import "./responsive.css";

const icons: Record<string, string> = {
  folder: '<path d="M3 6h7l2 2h9v11H3Z"/>', search: '<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
  grid: '<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',
  list: '<path d="M8 6h13M8 12h13M8 18h8"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/>',
  queue: '<path d="M4 6h12M4 12h12M4 18h8"/><path d="m16 17 2 2 4-5"/>', play: '<path d="m8 4 12 8-12 8Z"/>',
  report: '<path d="M6 3h9l4 4v14H6Z"/><path d="M14 3v5h5M9 13h7M9 17h7"/>',
  image: '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m4 17 5-5 4 4 2-2 5 5"/>',
  download: '<path d="M12 3v12m0 0 5-5m-5 5-5-5"/><path d="M5 20h14"/>',
  plus: '<path d="M12 5v14M5 12h14"/>', trash: '<path d="M4 7h16M9 7V4h6v3m-9 0 1 14h10l1-14M10 11v6M14 11v6"/>',
};
const icon = (name: string) => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg>`;
const help = (text: string) => `<span class="help-tip" tabindex="0" data-tooltip="${text.replace(/"/g, "&quot;")}">?</span>`;

document.querySelector<HTMLDivElement>("#app")!.innerHTML = `
<div class="app-shell">
  <header class="topbar"><div class="brand"><img class="brand-mark" src="${logoUrl}" alt=""/><div><strong>UI Studio</strong><small>Batch asset reskin workspace</small></div></div><div class="path-actions"><button id="choose-source">${icon("folder")} Source folder</button><button id="choose-output">${icon("folder")} Output folder</button><button id="dry-run">${icon("report")} Scan input</button></div><button id="open-resources" class="resource-button" title="Model resources" aria-label="Open model resources">${icon("download")}</button><div id="model-badge" class="model-badge"><i></i><span>FLUX.2 Klein 4B</span><b id="model-status">checking runtime</b></div></header>
  <main id="workspace">
    <aside class="left-panel"><section><label>Source root</label><div id="source-path" class="path-field">Not selected</div></section><section><label>Output root</label><div id="output-path" class="path-field">Not selected</div></section><section class="folder-section"><div class="section-title"><strong>Folders</strong><span id="folder-count">0</span></div><div id="folder-tree" class="folder-tree"><p>Select a source folder.</p></div></section><section class="inventory-summary"><div><b id="total-count">0</b><span>images</span></div><div><b id="issue-count">0</b><span>issues</span></div><div><b id="collision-count">0</b><span>collisions</span></div></section></aside>
    <div id="left-resizer" class="panel-resizer" title="Drag to resize folders"></div>
    <section class="browser-panel"><div class="browser-toolbar"><div class="asset-tabs"><button id="input-tab" class="active">Input</button><button id="output-tab">Output</button></div><div id="breadcrumbs" class="breadcrumbs"><button data-dir="">Input</button></div><div class="search-box">${icon("search")}<input id="search" placeholder="Search name or path"/></div><select id="status-filter" title="Filter by status"><option value="all">All status</option><option value="unprocessed">Unprocessed</option><option value="queued">Queued</option><option value="complete">Complete</option><option value="failed">Failed</option></select><select id="group-by" title="Group assets"><option value="none">Group: None</option><option value="name">Group: Name</option><option value="size">Group: Size</option><option value="dimensions">Group: Dimensions</option></select><div class="view-toggle"><button id="grid-view" class="active" title="Grid view">${icon("grid")}</button><button id="list-view" title="List view">${icon("list")}</button></div></div><div id="asset-grid" class="asset-grid"><div class="welcome">${icon("image")}<strong>Choose a source folder</strong><span>PNG, JPG, and JPEG files are scanned recursively.</span></div></div><footer><div id="status-progress" class="status-progress"></div><span id="visible-count">0 visible</span><span id="status-text">Ready</span><div id="selection-bar" class="footer-selection"><label><input id="select-visible" type="checkbox"/> Check visible</label><span id="selection-count">0 in queue</span><button id="clear-selection">Clear checked</button></div></footer></section>
    <div id="right-resizer" class="panel-resizer" title="Drag to resize controls"></div>
    <aside class="right-panel"><div class="right-panel-title">Style & batch</div><div class="right-scroll">
      <fieldset id="art-direction-panel"><legend>Art direction</legend><label>Style prompt<textarea id="style-prompt" rows="2" placeholder="e.g. painterly fantasy UI, soft carved edges"></textarea></label><div class="field-heading"><strong>Palette</strong>${help("Each percentage controls desired color dominance. Changing one automatically redistributes the others so the total remains 100%.")}</div><div id="palette-list" class="palette-list"></div><button id="add-color" class="wide add-color">${icon("plus")} Add color</button><div class="switch-row setting-switch"><div><span class="setting-title"><strong>Minimum working resolution</strong>${help("Turn this off to use the natural source or content-aware crop size. Model alignment can still add canvas padding.")}</span><small>Enlarge only assets below the selected size</small></div><label class="switch"><input id="minimum-resolution-enabled" type="checkbox"/><span></span></label></div><div class="model-controls-grid"><label><span class="label-with-help"><span id="denoise-label">Denoise strength · FLUX</span>${help("Higher values allow more change. Lower values preserve more of the source.")}</span><div class="range-control"><input id="denoise-strength" type="range" min="0" max="1" step="0.01"/><output id="denoise-strength-value">0.72</output></div></label><label id="working-resolution-setting">Minimum size<select id="working-resolution"><option value="256">256 px</option><option value="512">512 px</option><option value="768">768 px</option><option value="1024">1024 px</option><option value="2048">2048 px</option></select></label></div><div class="model-controls-grid secondary-controls"><label><span class="label-with-help"><span>Structure</span>${help("Controls source-image conditioning separately from denoise. Lower values allow a stronger redesign; higher values reproduce more source detail.")}</span><div class="range-control"><input id="structure-preservation" type="range" min="0" max="1" step="0.01"/><output id="structure-preservation-value">0.60</output></div></label><label>Quality steps<select id="inference-steps"><option value="4">4 · Fast</option><option value="8">8 · Balanced</option><option value="12">12 · Detailed</option></select></label></div><div class="check-with-help"><label class="check-row"><input id="content-aware-scaling" type="checkbox"/><span>Content-aware fit</span></label>${help("For transparent PNGs, process visible alpha bounds plus 6% padding instead of empty canvas. Original position and alpha are restored.")}</div></fieldset>
      <fieldset id="style-lock-panel"><legend>Style Lock</legend><div class="switch-row"><div><span class="setting-title"><strong>Lock batch style</strong>${help("Uses one reproducible style profile across the batch. Randomize the seed for a different consistent variation.")}</span><small>Same profile, seed, and model settings</small></div><label class="switch"><input id="style-lock-enabled" type="checkbox"/><span></span></label></div><div class="seed-setting"><span>Shared style seed</span><div class="seed-control"><button id="seed-decrement" type="button" title="Previous seed">‹</button><input id="style-seed" type="number" min="0" max="4294967295" step="1"/><button id="seed-increment" type="button" title="Next seed">›</button><button id="randomize-seed" type="button">Randomize</button></div></div><div id="style-fingerprint" class="profile-fingerprint">Profile not calculated</div></fieldset>
      <fieldset id="flux-lora-panel"><legend>FLUX LoRA</legend><div class="switch-row"><div><span class="setting-title"><strong>DreamRoom Objects LoRA</strong>${help("Available only with FLUX. Applies the Dream Room Studio object-detail training.")}</span><small>Built-in FLUX.2 LoRA</small></div><label class="switch"><input id="lora-enabled" type="checkbox"/><span></span></label></div><label>LoRA strength<input id="lora-strength" type="range" min="0" max="1.5" step="0.05"/><output id="lora-strength-value">1.00</output></label></fieldset>
      <fieldset class="batch-panel"><legend>Batch queue</legend><div class="queue-head"><b id="queue-count">0 queued</b><button id="clear-queue">Clear</button></div><div id="queue-list" class="queue-list"><p>Queue selected input assets to begin.</p></div><label class="check-row"><input id="overwrite" type="checkbox"/> <span>Overwrite existing files</span></label><button id="run-batch" class="wide primary">${icon("play")} Run FLUX reskin</button></fieldset>
    </div></aside>
  </main>
</div>
<div id="preview" class="preview" hidden><div class="preview-stage"><img id="preview-image" draggable="false"/></div><div class="preview-meta"><strong id="preview-name"></strong><span id="preview-info"></span></div><div class="preview-help">Wheel: zoom at cursor · Space-drag: pan · Esc/click outside: close</div></div>
<div id="comparison" class="modal" hidden><section class="comparison-dialog"><header><div><strong id="comparison-name">Before / after</strong><span id="comparison-info"></span></div><button id="close-comparison" title="Close">×</button></header><div class="compare"><figure><div class="checker"><img id="comparison-before"/></div><figcaption>Before</figcaption></figure><figure><div class="checker"><img id="comparison-after"/></div><figcaption>After</figcaption></figure></div></section></div>
<div id="preflight-modal" class="modal" hidden><section class="preflight-dialog" role="dialog" aria-modal="true" aria-labelledby="preflight-title"><header><div><strong id="preflight-title">PC compatibility check</strong><span>Required before downloading FLUX resources</span></div><button id="close-preflight" title="Close" aria-label="Close">×</button></header><div id="preflight-body" class="preflight-body"><div class="preflight-scanning"><i></i><strong>Checking this PC…</strong><span>GPU, NVIDIA driver, memory, processor, and storage</span></div></div><footer><button id="rescan-system" type="button">Scan again</button><button id="continue-downloads" class="primary" type="button" disabled>Open downloads</button></footer></section></div>
<div id="resources-modal" class="modal" hidden><section class="resources-dialog" role="dialog" aria-modal="true" aria-labelledby="resources-title"><header><div><strong id="resources-title">Model resources</strong><span>Local components required for portable AI processing</span></div><button id="close-resources" title="Close" aria-label="Close">×</button></header><div class="resources-summary"><div><b id="resources-installed">Checking…</b><span id="resources-summary-text">Reading local resource status</span><div id="download-meter" class="download-meter" hidden><i id="download-meter-fill"></i></div></div><button id="refresh-resources" type="button">Refresh status</button></div><div id="resources-list" class="resources-list"><p>Checking installed resources…</p></div><footer><span>Downloads resume automatically and are verified before installation.</span></footer></section></div>
<div id="color-picker" class="color-picker" hidden><canvas id="color-wheel" width="190" height="190"></canvas><label>Brightness<input id="color-value" type="range" min="0" max="1" step="0.01"/></label><label>Hex<input id="color-hex" type="text" maxlength="7" spellcheck="false"/></label><button id="close-color-picker">Done</button></div>
<div id="global-tooltip" class="global-tooltip" role="tooltip" hidden></div>`;

const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
const SETTINGS_SCOPE = await invoke<string>("settings_scope").catch(() => "development");
const SETTINGS_KEY = `ui-studio-settings-v2:${SETTINGS_SCOPE}`;
const defaultPalette: PaletteColor[] = [{ hex: "#182034", weight: 34 }, { hex: "#D6A84A", weight: 33 }, { hex: "#F4EAD5", weight: 33 }];
const defaults: Settings = { sourceRoot: "", outputRoot: "", stylePrompt: "", paletteColors: defaultPalette, loraEnabled: false, loraStrength: 1, fluxDenoisingStrength: 0.72, structurePreservation: 0.6, inferenceSteps: 8, overwrite: false, view: "grid", groupBy: "none", styleLockEnabled: true, styleSeed: 24681357, workingResolution: 1024, minimumResolutionEnabled: true, contentAwareScaling: true, leftPanelWidth: 240, rightPanelWidth: 380 };
let settings: Settings = { ...defaults, paletteColors: defaultPalette.map(color => ({ ...color })) };

function normalizeHex(value: string): string | null { const raw = value.trim().replace(/^#/, ""); return /^[0-9a-fA-F]{6}$/.test(raw) ? `#${raw.toUpperCase()}` : null; }
function distribute(total: number, weights: number[]): number[] { if (!weights.length) return []; const sum = weights.reduce((a, b) => a + Math.max(0, b), 0); const raw = weights.map(value => sum ? Math.max(0, value) / sum * total : total / weights.length); const values = raw.map(Math.floor); let remainder = total - values.reduce((a, b) => a + b, 0); raw.map((value, index) => ({ index, fraction: value - values[index] })).sort((a, b) => b.fraction - a.fraction).forEach(item => { if (remainder-- > 0) values[item.index]++; }); return values; }
function normalizePalette(colors: PaletteColor[]): PaletteColor[] { const valid = colors.map(color => ({ hex: normalizeHex(String(color.hex)) ?? "#808080", weight: Math.max(0, Number(color.weight) || 0) })); const weights = distribute(100, valid.map(color => color.weight)); return valid.map((color, index) => ({ ...color, weight: weights[index] })); }
try { const stored = JSON.parse(localStorage.getItem(SETTINGS_KEY) ?? "{}"); const legacy = typeof stored.palette === "string" ? (stored.palette.match(/#[0-9a-fA-F]{6}/g) ?? []) : []; const paletteColors = Array.isArray(stored.paletteColors) && stored.paletteColors.length ? stored.paletteColors : legacy.length ? legacy.map((hex: string) => ({ hex: hex.toUpperCase(), weight: 1 })) : settings.paletteColors; settings = { ...settings, ...stored, paletteColors: normalizePalette(paletteColors) }; } catch { settings = { ...defaults, paletteColors: defaultPalette.map(color => ({ ...color })) }; }

let inventory: InventoryReport | null = null, outputInventory: InventoryReport | null = null;
let activeView: "input" | "output" = "input", currentDir = "";
let selected = new Set<string>(), queue = new Map<string, QueueStatus>(), results = new Map<string, ProcessResult>(), blobUrls = new Map<string, string>();
let fluxAvailable: boolean | undefined;
type RuntimeResource = { id: string; group: string; name: string; description: string; path: string; available: boolean; optional?: boolean; downloadBytes?: number; sizeEstimated?: boolean };
type RuntimeProbe = { available: boolean; engine: string; missing: string[]; resources: RuntimeResource[] };
type DownloadResult = { resourceId: string; files: number; bytes: number };
type DownloadProgress = { resourceId: string; fileName: string; downloadedBytes: number; totalBytes?: number; resumedBytes: number; attempt: number; phase: "downloading" | "resuming" | "retrying" | "verifying" | "complete" };
type GpuInfo = { name: string; memoryMib: number; driverVersion: string };
type SystemScan = { compatible: boolean; nvidiaDetected: boolean; cudaAvailable: boolean; cudaVersion?: string; gpus: GpuInfo[]; cpuName: string; logicalCores: number; memoryBytes?: number; freeDiskBytes?: number; osName: string; warning?: string };
let runtimeResources: RuntimeResource[] = [];
let resourceDownloadActive = false;
let activeDownloadPosition = "";
let systemScanActive = false, downloadHardwareApproved = false;
let runtimeBlockingMessage = "";
let paletteEditingIndex: number | null = null, pickerHue = 0, pickerSaturation = 0, pickerValue = 1;

function activeInventory(): InventoryReport | null { return activeView === "input" ? inventory : outputInventory; }
function palettePrompt(): string { return settings.paletteColors.map(color => `${color.hex} ${color.weight}%`).join(", "); }
function persist(): void { const denoise = Math.max(0, Math.min(1, Number($<HTMLInputElement>("#denoise-strength").value) || 0)); settings = { ...settings, stylePrompt: $<HTMLTextAreaElement>("#style-prompt").value, loraEnabled: $<HTMLInputElement>("#lora-enabled").checked, loraStrength: Math.max(0, Math.min(1.5, Number($<HTMLInputElement>("#lora-strength").value) || 0)), fluxDenoisingStrength: denoise, structurePreservation: Math.max(0, Math.min(1, Number($<HTMLInputElement>("#structure-preservation").value) || 0)), inferenceSteps: Number($<HTMLSelectElement>("#inference-steps").value) as Settings["inferenceSteps"], overwrite: $<HTMLInputElement>("#overwrite").checked, groupBy: $<HTMLSelectElement>("#group-by").value as Settings["groupBy"], styleLockEnabled: $<HTMLInputElement>("#style-lock-enabled").checked, styleSeed: Math.max(0, Math.min(4294967295, Number($<HTMLInputElement>("#style-seed").value) || defaults.styleSeed)), workingResolution: Number($<HTMLSelectElement>("#working-resolution").value) as Settings["workingResolution"], minimumResolutionEnabled: $<HTMLInputElement>("#minimum-resolution-enabled").checked, contentAwareScaling: $<HTMLInputElement>("#content-aware-scaling").checked }; localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); renderStyleFingerprint(); }
function styleFingerprint(): string { const profile = JSON.stringify({ model: "FLUX.2 Klein 4B", style: settings.stylePrompt.trim().replace(/\s+/g, " "), palette: settings.paletteColors, seed: settings.styleLockEnabled ? settings.styleSeed : null, lora: settings.loraEnabled ? { name: "DreamRoom-Objects-v1", strength: settings.loraStrength } : null, denoisingStrength: settings.fluxDenoisingStrength, structurePreservation: settings.structurePreservation, minimumResolutionEnabled: settings.minimumResolutionEnabled, resolution: settings.minimumResolutionEnabled ? settings.workingResolution : null, contentAwareScaling: settings.contentAwareScaling, steps: settings.inferenceSteps }); let hash = 2166136261; for (let index = 0; index < profile.length; index++) { hash ^= profile.charCodeAt(index); hash = Math.imul(hash, 16777619); } return `STYLE-${(hash >>> 0).toString(16).padStart(8, "0").toUpperCase()}`; }
function renderStyleFingerprint(): void { $("#style-fingerprint").textContent = `${styleFingerprint()} · ${settings.styleLockEnabled ? "locked" : "unlocked"}`; }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!)); }
function formatBytes(bytes: number): string { if (!Number.isFinite(bytes) || bytes < 0) return "Size unknown"; const units = ["B", "KB", "MB", "GB", "TB"]; let value = bytes, unit = 0; while (value >= 1024 && unit < units.length - 1) { value /= 1024; unit++; } return `${value.toFixed(unit === 0 ? 0 : value >= 10 ? 1 : 2)} ${units[unit]}`; }
await listen<DownloadProgress>("resource-download-progress", event => {
  if (!resourceDownloadActive) return;
  const progress = event.payload, meter = $("#download-meter"), fill = $("#download-meter-fill");
  meter.hidden = false;
  const percent = progress.totalBytes && progress.totalBytes > 0 ? Math.min(100, progress.downloadedBytes / progress.totalBytes * 100) : 0;
  meter.classList.toggle("indeterminate", !progress.totalBytes);
  fill.style.width = `${percent}%`;
  const amount = progress.totalBytes ? `${formatBytes(progress.downloadedBytes)} / ${formatBytes(progress.totalBytes)} · ${percent.toFixed(1)}%` : formatBytes(progress.downloadedBytes);
  const action = progress.phase === "retrying" ? `Connection interrupted · retrying ${progress.attempt + 1}/5` : progress.phase === "verifying" ? "Verifying download" : progress.phase === "complete" ? "Download complete" : progress.resumedBytes > 0 ? `Resuming from ${formatBytes(progress.resumedBytes)}` : "Downloading";
  $("#resources-summary-text").textContent = `${action} · ${progress.fileName} · ${amount}${activeDownloadPosition}`;
});
function setStatus(value: string, progress: "idle" | "running" | "complete" | "failed" = "idle"): void { $("#status-text").textContent = runtimeBlockingMessage || value; $("#status-progress").className = `status-progress ${runtimeBlockingMessage ? "failed" : progress}`; }
function showTooltip(anchor: HTMLElement): void { const tooltip = $("#global-tooltip"); tooltip.textContent = anchor.dataset.tooltip ?? ""; tooltip.hidden = false; const rect = anchor.getBoundingClientRect(), tip = tooltip.getBoundingClientRect(), margin = 10; let left = rect.right - tip.width, top = rect.top - tip.height - 8; left = Math.max(margin, Math.min(window.innerWidth - tip.width - margin, left)); if (top < margin) top = Math.min(window.innerHeight - tip.height - margin, rect.bottom + 8); tooltip.style.left = `${Math.round(left)}px`; tooltip.style.top = `${Math.round(top)}px`; }
function hideTooltip(): void { $("#global-tooltip").hidden = true; }
function parentDir(value: string): string { const parts = value.replace(/\\/g, "/").replace(/^\/+|\/+$/g, "").split("/").filter(Boolean); parts.pop(); return parts.join("/"); }
async function imageUrl(path: string): Promise<string> { const cached = blobUrls.get(path); if (cached) return cached; const bytes = await invoke<number[]>("read_binary", { path }); const url = URL.createObjectURL(new Blob([new Uint8Array(bytes)], { type: `image/${path.toLowerCase().endsWith(".png") ? "png" : "jpeg"}` })); blobUrls.set(path, url); return url; }

async function scanInput(root = settings.sourceRoot): Promise<void> { if (!root) return; setStatus("Scanning input…", "running"); try { inventory = await invoke<InventoryReport>("inventory_folder", { root }); settings.sourceRoot = inventory.root; activeView = "input"; currentDir = ""; selected.clear(); queue.clear(); results.clear(); outputInventory = null; persist(); $("#source-path").textContent = inventory.root; renderAll(); setStatus(`Input ready · ${inventory.assets.length} images`, "complete"); } catch (error) { setStatus(`Scan failed: ${String(error)}`, "failed"); } }
async function scanOutput(silent = false): Promise<void> { if (!settings.outputRoot) { outputInventory = null; renderAll(); return; } if (!silent) setStatus("Scanning output…", "running"); try { outputInventory = await invoke<InventoryReport>("inventory_folder", { root: settings.outputRoot }); renderAll(); if (!silent) setStatus(`Output ready · ${outputInventory.assets.length} images`, "complete"); } catch (error) { outputInventory = null; renderAll(); if (!silent) setStatus(`Output scan failed: ${String(error)}`, "failed"); } }
function allFolders(): string[] { const inv = activeInventory(); if (!inv) return []; const dirs = new Set<string>(); for (const asset of inv.assets) { let dir = asset.directory; while (dir) { dirs.add(dir); dir = parentDir(dir); } } return [...dirs].sort((a, b) => a.localeCompare(b)); }
function renderFolders(): void { const inv = activeInventory(), folders = allFolders(); $("#folder-count").textContent = String(folders.length); if (!inv) { $("#folder-tree").innerHTML = `<p>${activeView === "input" ? "Select a source folder." : "No output images yet."}</p>`; return; } const items = [`<button data-dir="" class="${currentDir === "" ? "active" : ""}">${icon("folder")}<span>All ${activeView}</span><b>${inv.assets.length}</b></button>`]; for (const folder of folders) { const depth = folder.split("/").length - 1, count = inv.assets.filter(asset => asset.directory === folder).length; items.push(`<button data-dir="${escapeHtml(folder)}" class="${currentDir === folder ? "active" : ""}" style="--depth:${depth}">${icon("folder")}<span>${escapeHtml(folder.split("/").pop()!)}</span><b>${count}</b></button>`); } $("#folder-tree").innerHTML = items.join(""); $("#folder-tree").querySelectorAll<HTMLButtonElement>("button").forEach(button => button.onclick = () => { currentDir = button.dataset.dir ?? ""; renderAll(); }); }
function renderBreadcrumbs(): void { const parts = currentDir.split("/").filter(Boolean); let accumulated = ""; $("#breadcrumbs").innerHTML = parts.length ? `<button data-dir="">All</button>` + parts.map(part => { accumulated = accumulated ? `${accumulated}/${part}` : part; return `<i>›</i><button data-dir="${escapeHtml(accumulated)}">${escapeHtml(part)}</button>`; }).join("") : ""; $("#breadcrumbs").querySelectorAll<HTMLButtonElement>("button").forEach(button => button.onclick = () => { currentDir = button.dataset.dir ?? ""; renderAll(); }); }
function visibleAssets(): AssetInfo[] { const inv = activeInventory(); if (!inv) return []; const query = $<HTMLInputElement>("#search").value.trim().toLowerCase(), filter = $<HTMLSelectElement>("#status-filter").value; return inv.assets.filter(asset => (!currentDir || asset.directory === currentDir) && (!query || asset.relativePath.toLowerCase().includes(query)) && (activeView === "output" || filter === "all" || (filter === "unprocessed" ? !queue.has(asset.relativePath) : queue.get(asset.relativePath) === filter))); }
function statusLabel(path: string): string { return queue.get(path) ?? "unprocessed"; }
type AssetGroup = { label: string; order: number; assets: AssetInfo[] };
function groupedAssets(assets: AssetInfo[]): AssetGroup[] {
  if (settings.groupBy === "none") return [{ label: "", order: 0, assets }];
  const groups = new Map<string, AssetGroup>();
  for (const asset of assets) {
    let label = "Other", order = Number.MAX_SAFE_INTEGER;
    if (settings.groupBy === "name") {
      const first = asset.filename.trim().charAt(0).toUpperCase();
      if (first >= "A" && first <= "H") [label, order] = ["A – H", 0];
      else if (first >= "I" && first <= "P") [label, order] = ["I – P", 1];
      else if (first >= "Q" && first <= "Z") [label, order] = ["Q – Z", 2];
      else if (first >= "0" && first <= "9") [label, order] = ["0 – 9", 3];
      else [label, order] = ["Other", 4];
    } else if (settings.groupBy === "size") {
      if (asset.bytes < 16 * 1024) [label, order] = ["Tiny (under 16 KB)", 0];
      else if (asset.bytes < 1024 * 1024) [label, order] = ["Small (16 KB – 1 MB)", 1];
      else if (asset.bytes < 128 * 1024 * 1024) [label, order] = ["Medium (1 – 128 MB)", 2];
      else if (asset.bytes < 1024 * 1024 * 1024) [label, order] = ["Large (128 MB – 1 GB)", 3];
      else [label, order] = ["Huge (1 GB or larger)", 4];
    } else {
      const longestSide = Math.max(asset.width, asset.height);
      if (longestSide <= 256) [label, order] = ["256", 0];
      else if (longestSide <= 512) [label, order] = ["512", 1];
      else if (longestSide <= 768) [label, order] = ["768", 2];
      else if (longestSide <= 1024) [label, order] = ["1024", 3];
      else [label, order] = ["2048", 4];
    }
    const existing = groups.get(label);
    if (existing) existing.assets.push(asset);
    else groups.set(label, { label, order, assets: [asset] });
  }
  return [...groups.values()]
    .sort((a, b) => a.order - b.order || a.label.localeCompare(b.label, undefined, { numeric: true }))
    .map(group => ({ ...group, assets: group.assets.sort((a, b) => a.filename.localeCompare(b.filename, undefined, { numeric: true })) }));
}
function assetCardHtml(asset: AssetInfo, input: boolean): string { return `<article class="asset-card ${input && selected.has(asset.relativePath) ? "selected" : ""}" data-path="${escapeHtml(asset.relativePath)}"><div class="thumb checker"><div class="thumb-loading">Loading…</div><img alt="${escapeHtml(asset.filename)}"/></div><div class="asset-text"><strong title="${escapeHtml(asset.relativePath)}">${escapeHtml(asset.filename)}</strong><span>${asset.width} × ${asset.height} · ${asset.extension.toUpperCase()}${asset.hasAlpha ? " · alpha" : ""}</span></div>${input ? `<label class="card-check"><input type="checkbox" ${selected.has(asset.relativePath) ? "checked" : ""}/><span></span></label><i class="asset-status ${statusLabel(asset.relativePath)}">${statusLabel(asset.relativePath)}</i>` : '<i class="asset-status complete">output</i>'}</article>`; }
function renderAssets(): void {
  const inv = activeInventory(), assets = visibleAssets(), input = activeView === "input", grid = $("#asset-grid");
  grid.className = `asset-grid ${settings.view === "list" ? "list" : ""} ${settings.groupBy !== "none" ? "grouped" : ""}`;
  $("#visible-count").textContent = `${assets.length} visible`;
  if (!inv) { grid.innerHTML = `<div class="welcome">${icon("image")}<strong>${input ? "Choose a source folder" : "No output images"}</strong><span>${input ? "PNG, JPG, and JPEG files are scanned recursively." : "Run a batch or choose an output folder containing images."}</span></div>`; return; }
  if (!assets.length) { grid.innerHTML = '<div class="welcome"><strong>No matching images</strong><span>Change folder or search.</span></div>'; return; }
  const groups = groupedAssets(assets);
  grid.innerHTML = groups.map((group, index) => {
    const ready = group.assets.every(asset => selected.has(asset.relativePath) && ["queued", "complete"].includes(statusLabel(asset.relativePath)));
    const header = settings.groupBy === "none" ? "" : `<div class="asset-group-header"><div><strong>${escapeHtml(group.label)}</strong><span>${group.assets.length} item${group.assets.length === 1 ? "" : "s"}</span></div>${input ? `<button type="button" data-group-index="${index}" ${ready ? "disabled" : ""}>${ready ? "Queued" : `${icon("queue")} Queue group`}</button>` : ""}</div>`;
    return header + group.assets.map(asset => assetCardHtml(asset, input)).join("");
  }).join("");
  grid.querySelectorAll<HTMLButtonElement>(".asset-group-header button:not(:disabled)").forEach(button => button.onclick = () => { const group = groups[Number(button.dataset.groupIndex)]; if (!group) return; for (const asset of group.assets) { selected.add(asset.relativePath); const state = queue.get(asset.relativePath); if (!state || state === "failed" || state === "skipped") queue.set(asset.relativePath, "queued"); } renderAll(); });
  grid.querySelectorAll<HTMLElement>(".asset-card").forEach(card => { const path = card.dataset.path!, asset = inv.assets.find(item => item.relativePath === path)!; imageUrl(asset.path).then(url => { const image = card.querySelector<HTMLImageElement>("img")!; image.src = url; image.onload = () => card.querySelector(".thumb-loading")?.remove(); }).catch(() => { card.querySelector<HTMLElement>(".thumb-loading")!.textContent = "Preview failed"; }); const checkbox = card.querySelector<HTMLInputElement>("input"); if (checkbox) checkbox.onchange = event => { const checked = (event.target as HTMLInputElement).checked; if (checked) { selected.add(path); if (!queue.has(path)) queue.set(path, "queued"); } else { selected.delete(path); queue.delete(path); } renderAll(); }; card.ondblclick = () => input ? openInputAsset(asset) : openPreview(asset); });
}
function renderSelection(): void { const assets = visibleAssets(); $("#selection-bar").hidden = activeView === "output"; $("#status-filter").hidden = activeView === "output"; $("#selection-count").textContent = `${queue.size} in queue`; $<HTMLInputElement>("#select-visible").checked = activeView === "input" && assets.length > 0 && assets.every(asset => selected.has(asset.relativePath)); }
function renderQueue(): void { const list = $("#queue-list"), repaintable = [...queue.values()].filter(state => state === "queued" || state === "complete").length; $("#queue-count").textContent = `${repaintable} ready · ${queue.size} total`; if (!queue.size) { list.innerHTML = "<p>Check input assets to add them automatically.</p>"; return; } list.innerHTML = [...queue].map(([path, state]) => `<button data-path="${escapeHtml(path)}"><span title="${escapeHtml(path)}">${escapeHtml(path.split("/").pop()!)}</span><i class="${state}">${state}</i></button>`).join(""); list.querySelectorAll<HTMLButtonElement>("button").forEach(button => button.onclick = () => { const path = button.dataset.path!, state = queue.get(path), asset = inventory?.assets.find(item => item.relativePath === path); if (state === "complete") openComparison(path); else if (asset) openPreview(asset); }); }
function renderSummary(): void { const inv = activeInventory(); $("#total-count").textContent = String(inv?.assets.length ?? 0); $("#issue-count").textContent = String(inv?.issues.length ?? 0); $("#collision-count").textContent = String(inv?.collisions.length ?? 0); }
function renderAll(): void { $("#input-tab").classList.toggle("active", activeView === "input"); $("#output-tab").classList.toggle("active", activeView === "output"); renderFolders(); renderBreadcrumbs(); renderAssets(); renderSelection(); renderQueue(); renderSummary(); }

async function openPreview(asset: AssetInfo): Promise<void> { const preview = $("#preview"), image = $<HTMLImageElement>("#preview-image"); image.src = await imageUrl(asset.path); image.style.transform = "translate(0px,0px) scale(1)"; $("#preview-name").textContent = asset.relativePath; $("#preview-info").textContent = `${asset.width} × ${asset.height} · ${asset.extension.toUpperCase()}${asset.hasAlpha ? " · transparency" : ""}`; preview.hidden = false; setupPanZoom(preview, image); }
async function openInputAsset(asset: AssetInfo): Promise<void> { if (settings.outputRoot && !outputInventory) await scanOutput(true); const output = outputInventory?.assets.find(item => item.relativePath === asset.relativePath); if (output) await openComparison(asset.relativePath); else await openPreview(asset); }
async function openComparison(path: string): Promise<void> { const source = inventory?.assets.find(asset => asset.relativePath === path), result = results.get(path), output = outputInventory?.assets.find(asset => asset.relativePath === path); if (!source || (!result?.outputPath && !output)) { setStatus("The completed output is not available for comparison."); return; } $("#comparison-name").textContent = path; $("#comparison-info").textContent = result?.message ?? "Completed output"; $<HTMLImageElement>("#comparison-before").src = await imageUrl(source.path); $<HTMLImageElement>("#comparison-after").src = await imageUrl(result?.outputPath ?? output!.path); $("#comparison").hidden = false; }
let teardownPanZoom: (() => void) | null = null;
function closePreview(): void { $("#preview").hidden = true; teardownPanZoom?.(); teardownPanZoom = null; }
function setupPanZoom(container: HTMLElement, image: HTMLImageElement): void { teardownPanZoom?.(); let scale = 1, x = 0, y = 0, space = false, dragging = false, px = 0, py = 0; const draw = () => image.style.transform = `translate(${x}px,${y}px) scale(${scale})`; const editable = (target: EventTarget | null) => target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || (target instanceof HTMLElement && target.isContentEditable); const wheel = (event: WheelEvent) => { event.preventDefault(); const old = scale; scale = Math.max(.1, Math.min(12, scale * (event.deltaY < 0 ? 1.16 : .86))); const rect = image.getBoundingClientRect(); x -= (event.clientX - rect.left - rect.width / 2) * (scale / old - 1); y -= (event.clientY - rect.top - rect.height / 2) * (scale / old - 1); draw(); }; const keydown = (event: KeyboardEvent) => { if (container.hidden || editable(event.target)) return; if (event.code === "Space") { space = true; event.preventDefault(); } if (event.key === "Escape") closePreview(); }; const keyup = (event: KeyboardEvent) => { if (event.code === "Space") space = false; }; const down = (event: PointerEvent) => { if (!space) return; dragging = true; px = event.clientX; py = event.clientY; container.setPointerCapture(event.pointerId); }; const move = (event: PointerEvent) => { if (!dragging) return; x += event.clientX - px; y += event.clientY - py; px = event.clientX; py = event.clientY; draw(); }; const up = () => dragging = false; container.addEventListener("wheel", wheel, { passive: false }); container.addEventListener("pointerdown", down); container.addEventListener("pointermove", move); container.addEventListener("pointerup", up); window.addEventListener("keydown", keydown); window.addEventListener("keyup", keyup); teardownPanZoom = () => { container.removeEventListener("wheel", wheel); container.removeEventListener("pointerdown", down); container.removeEventListener("pointermove", move); container.removeEventListener("pointerup", up); window.removeEventListener("keydown", keydown); window.removeEventListener("keyup", keyup); }; }

function setWeight(index: number, requested: number): void { const colors = settings.paletteColors; if (!colors[index]) return; if (colors.length === 1) colors[0].weight = 100; else { const target = Math.max(0, Math.min(100, Math.round(requested))), others = colors.map((_, i) => i).filter(i => i !== index), redistributed = distribute(100 - target, others.map(i => colors[i].weight)); colors[index].weight = target; others.forEach((colorIndex, i) => colors[colorIndex].weight = redistributed[i]); } persist(); renderPalette(); }
function addColor(): void { const presets = ["#8D6CFF", "#3AB7A8", "#E46C78", "#E7C75A", "#5F83D9"], share = Math.max(1, Math.floor(100 / (settings.paletteColors.length + 1))), existing = distribute(100 - share, settings.paletteColors.map(color => color.weight)); settings.paletteColors.forEach((color, index) => color.weight = existing[index]); settings.paletteColors.push({ hex: presets[settings.paletteColors.length % presets.length], weight: share }); persist(); renderPalette(); }
function removeColor(index: number): void { settings.paletteColors.splice(index, 1); settings.paletteColors = normalizePalette(settings.paletteColors); if (paletteEditingIndex === index) closeColorPicker(); persist(); renderPalette(); }
function renderPalette(): void { const list = $("#palette-list"); if (!settings.paletteColors.length) { list.innerHTML = '<div class="empty-palette">No palette colors. Add one to guide the model.</div>'; return; } list.innerHTML = settings.paletteColors.map((color, index) => `<div class="palette-row" data-index="${index}"><button class="color-swatch" style="background:${color.hex}" title="Edit ${color.hex}"><span>${color.hex}</span></button><div class="percent-control"><button class="percent-down" title="Decrease by 5">◀</button><div class="percent-value"><input type="number" min="0" max="100" step="5" value="${color.weight}"/><span>%</span></div><button class="percent-up" title="Increase by 5">▶</button></div><button class="delete-color" title="Delete color">${icon("trash")}</button></div>`).join(""); list.querySelectorAll<HTMLElement>(".palette-row").forEach(row => { const index = Number(row.dataset.index); row.querySelector<HTMLButtonElement>(".color-swatch")!.onclick = event => openColorPicker(index, event.currentTarget as HTMLElement); row.querySelector<HTMLInputElement>("input")!.onchange = event => setWeight(index, Number((event.target as HTMLInputElement).value)); row.querySelector<HTMLButtonElement>(".percent-up")!.onclick = () => setWeight(index, settings.paletteColors[index].weight + 5); row.querySelector<HTMLButtonElement>(".percent-down")!.onclick = () => setWeight(index, settings.paletteColors[index].weight - 5); row.querySelector<HTMLButtonElement>(".delete-color")!.onclick = () => removeColor(index); }); }
function hexToRgb(hex: string): [number, number, number] { const value = parseInt(hex.slice(1), 16); return [(value >> 16) & 255, (value >> 8) & 255, value & 255]; }
function rgbToHex(r: number, g: number, b: number): string { return `#${[r, g, b].map(value => Math.round(value).toString(16).padStart(2, "0")).join("").toUpperCase()}`; }
function rgbToHsv(r: number, g: number, b: number): [number, number, number] { r /= 255; g /= 255; b /= 255; const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min; let h = 0; if (d) h = max === r ? ((g - b) / d) % 6 : max === g ? (b - r) / d + 2 : (r - g) / d + 4; return [((h * 60) + 360) % 360, max ? d / max : 0, max]; }
function hsvToRgb(h: number, s: number, v: number): [number, number, number] { const c = v * s, x = c * (1 - Math.abs((h / 60) % 2 - 1)), m = v - c, values = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x]; return values.map(value => (value + m) * 255) as [number, number, number]; }
function drawColorWheel(): void { const canvas = $<HTMLCanvasElement>("#color-wheel"), context = canvas.getContext("2d")!, radius = canvas.width / 2, data = context.createImageData(canvas.width, canvas.height); for (let y = 0; y < canvas.height; y++) for (let x = 0; x < canvas.width; x++) { const dx = x + .5 - radius, dy = y + .5 - radius, sat = Math.sqrt(dx * dx + dy * dy) / (radius - 3), offset = (y * canvas.width + x) * 4; if (sat <= 1) { const hue = (Math.atan2(dy, dx) * 180 / Math.PI + 360) % 360, [r, g, b] = hsvToRgb(hue, sat, pickerValue); data.data.set([r, g, b, 255], offset); } } context.putImageData(data, 0, 0); const angle = pickerHue * Math.PI / 180, distance = pickerSaturation * (radius - 3); context.beginPath(); context.arc(radius + Math.cos(angle) * distance, radius + Math.sin(angle) * distance, 6, 0, Math.PI * 2); context.strokeStyle = pickerValue > .55 ? "#111" : "#fff"; context.lineWidth = 2; context.stroke(); }
function applyPickerColor(): void { if (paletteEditingIndex === null || !settings.paletteColors[paletteEditingIndex]) return; const hex = rgbToHex(...hsvToRgb(pickerHue, pickerSaturation, pickerValue)); settings.paletteColors[paletteEditingIndex].hex = hex; $<HTMLInputElement>("#color-hex").value = hex; const swatch = document.querySelector<HTMLElement>(`.palette-row[data-index="${paletteEditingIndex}"] .color-swatch`); if (swatch) { swatch.style.background = hex; swatch.querySelector("span")!.textContent = hex; } persist(); drawColorWheel(); }
function openColorPicker(index: number, anchor: HTMLElement): void { paletteEditingIndex = index; [pickerHue, pickerSaturation, pickerValue] = rgbToHsv(...hexToRgb(settings.paletteColors[index].hex)); $<HTMLInputElement>("#color-value").value = String(pickerValue); $<HTMLInputElement>("#color-hex").value = settings.paletteColors[index].hex; const picker = $("#color-picker"), rect = anchor.getBoundingClientRect(); picker.hidden = false; picker.style.left = `${Math.max(10, rect.left - 224)}px`; picker.style.top = `${Math.max(70, Math.min(window.innerHeight - 330, rect.top - 80))}px`; drawColorWheel(); }
function closeColorPicker(): void { $("#color-picker").hidden = true; paletteEditingIndex = null; }

function updateResolutionNote(): void { const enabled = $<HTMLInputElement>("#minimum-resolution-enabled").checked; $<HTMLSelectElement>("#working-resolution").disabled = !enabled; $("#working-resolution-setting").classList.toggle("inactive", !enabled); persist(); }
function setSeed(value: number): void { $<HTMLInputElement>("#style-seed").value = String(Math.max(0, Math.min(4294967295, Math.trunc(value)))); persist(); }
function runtimeIssue(): string { const ids = ["flux-runtime", "flux-transformer", "flux-text-encoder", "flux-vae", "flux-tokenizer", ...(settings.loraEnabled ? ["dreamroom-lora"] : [])]; const missing = runtimeResources.filter(resource => ids.includes(resource.id) && !resource.available); if (!missing.length && fluxAvailable !== false) return ""; if (!missing.length) return "Missing required FLUX runtime or model resources · open Downloads"; const names = missing.slice(0, 2).map(resource => resource.name); const remainder = missing.length - names.length; return `Missing ${names.join(" and ")}${remainder ? ` + ${remainder} more` : ""} · open Downloads`; }
function updateRuntimeState(): void {
  const available = fluxAvailable, issue = runtimeIssue(), unavailable = Boolean(issue), wasBlocked = Boolean(runtimeBlockingMessage);
  $<HTMLInputElement>("#denoise-strength").value = String(settings.fluxDenoisingStrength); $("#denoise-strength-value").textContent = settings.fluxDenoisingStrength.toFixed(2);
  for (const selector of ["#art-direction-panel", "#style-lock-panel"]) { const panel = $<HTMLFieldSetElement>(selector); panel.disabled = unavailable; panel.classList.toggle("runtime-unavailable", unavailable); }
  $<HTMLInputElement>("#denoise-strength").disabled = unavailable; $<HTMLInputElement>("#structure-preservation").disabled = unavailable; $<HTMLSelectElement>("#inference-steps").disabled = unavailable;
  const loraPanel = $<HTMLFieldSetElement>("#flux-lora-panel"), baseFluxMissing = fluxAvailable === false; loraPanel.disabled = baseFluxMissing; loraPanel.classList.toggle("runtime-unavailable", baseFluxMissing); $<HTMLInputElement>("#lora-enabled").disabled = baseFluxMissing; $<HTMLInputElement>("#lora-strength").disabled = unavailable;
  $<HTMLInputElement>("#overwrite").disabled = unavailable;
  const run = $<HTMLButtonElement>("#run-batch"); run.classList.toggle("runtime-required", unavailable); run.setAttribute("aria-disabled", String(unavailable));
  $("#model-status").textContent = available === undefined ? "checking runtime" : available && !issue ? "runtime ready" : "runtime missing"; $("#model-badge").classList.toggle("ready", available === true && !issue);
  runtimeBlockingMessage = issue; if (issue) setStatus(issue, "failed"); else if (wasBlocked) setStatus("Ready");
  persist();
}
function showResourcesModal(): void { renderResources(); $("#resources-modal").hidden = false; }
function renderSystemScan(scan: SystemScan): void {
  const gpu = scan.gpus[0], gpuName = gpu?.name ?? "No NVIDIA GPU detected", gpuDetail = gpu ? `${(gpu.memoryMib / 1024).toFixed(1)} GB VRAM · driver ${escapeHtml(gpu.driverVersion)}` : "A CUDA-capable NVIDIA GPU is required";
  $("#preflight-body").innerHTML = `<div class="preflight-result ${scan.compatible ? "compatible" : "blocked"}"><div class="preflight-verdict"><i>${scan.compatible ? "✓" : "!"}</i><div><strong>${scan.compatible ? "This PC can run FLUX" : "Downloads blocked on this PC"}</strong><span>${scan.compatible ? "NVIDIA GPU and CUDA driver support detected" : "Install a supported NVIDIA GPU and current NVIDIA driver before downloading"}</span></div></div><div class="spec-grid"><article><span>Graphics</span><strong>${escapeHtml(gpuName)}</strong><small>${gpuDetail}</small></article><article><span>CUDA support</span><strong>${scan.cudaAvailable ? `Ready${scan.cudaVersion ? ` · ${escapeHtml(scan.cudaVersion)}` : ""}` : "Unavailable"}</strong><small>${scan.nvidiaDetected ? "Provided by the installed NVIDIA driver" : "NVIDIA driver query failed"}</small></article><article><span>System memory</span><strong>${scan.memoryBytes === undefined ? "Unknown" : formatBytes(scan.memoryBytes)}</strong><small>${escapeHtml(scan.osName)}</small></article><article><span>Processor</span><strong>${escapeHtml(scan.cpuName)}</strong><small>${scan.logicalCores} logical processors</small></article><article class="spec-wide"><span>Free space on app drive</span><strong>${scan.freeDiskBytes === undefined ? "Unknown" : formatBytes(scan.freeDiskBytes)}</strong><small>30 GB free is recommended for downloads and installation</small></article></div>${scan.warning ? `<div class="preflight-warning">${escapeHtml(scan.warning)}</div>` : ""}</div>`;
  downloadHardwareApproved = scan.compatible;
  $<HTMLButtonElement>("#continue-downloads").disabled = !scan.compatible;
  $<HTMLButtonElement>("#continue-downloads").title = scan.compatible ? "Open verified resource downloads" : "Downloads require an NVIDIA CUDA-capable GPU";
  renderResources();
}
async function scanHardware(): Promise<void> {
  if (systemScanActive) return;
  systemScanActive = true; downloadHardwareApproved = false; $("#preflight-modal").hidden = false;
  $("#preflight-body").innerHTML = '<div class="preflight-scanning"><i></i><strong>Checking this PC…</strong><span>GPU, NVIDIA driver, memory, processor, and storage</span></div>';
  $<HTMLButtonElement>("#rescan-system").disabled = true; $<HTMLButtonElement>("#continue-downloads").disabled = true;
  try { renderSystemScan(await invoke<SystemScan>("scan_system")); }
  catch (error) { renderSystemScan({ compatible: false, nvidiaDetected: false, cudaAvailable: false, gpus: [], cpuName: "Unknown", logicalCores: navigator.hardwareConcurrency || 1, osName: "Windows", warning: `Hardware scan failed: ${String(error)} Downloads remain disabled.` }); }
  finally { systemScanActive = false; $<HTMLButtonElement>("#rescan-system").disabled = false; }
}
function openResourcesModal(): void { void scanHardware(); }
function renderResources(): void {
  const required = runtimeResources.filter(resource => !resource.optional), installed = required.filter(resource => resource.available).length, missing = required.length - installed, statusUnavailable = runtimeResources.length === 0, downloadLocked = !downloadHardwareApproved;
  $("#open-resources").classList.toggle("needs-download", missing > 0 || statusUnavailable); $("#resources-installed").textContent = runtimeResources.length ? `${installed} of ${required.length} required installed` : "Resource status unavailable"; $("#resources-summary-text").textContent = runtimeResources.length ? missing ? `${missing} required component${missing === 1 ? " is" : "s are"} missing` : "All required model components are ready" : "Refresh to check the local installation";
  if (!runtimeResources.length) { $("#resources-list").innerHTML = "<p>No resource inventory was returned.</p>"; return; }
  const groupOrder = ["FLUX.2 Klein 4B", "FLUX LoRA"], resourceOrder = ["flux-runtime", "flux-transformer", "flux-text-encoder", "flux-vae", "flux-tokenizer", "dreamroom-lora"];
  const groups = [...new Set(runtimeResources.map(resource => resource.group))].sort((a, b) => (groupOrder.indexOf(a) < 0 ? 99 : groupOrder.indexOf(a)) - (groupOrder.indexOf(b) < 0 ? 99 : groupOrder.indexOf(b)));
  $("#resources-list").classList.toggle("hardware-blocked", downloadLocked);
  $("#resources-list").innerHTML = groups.map(group => { const groupResources = runtimeResources.filter(resource => resource.group === group).sort((a, b) => resourceOrder.indexOf(a.id) - resourceOrder.indexOf(b.id)), groupReady = groupResources.every(resource => resource.available), groupBytes = groupResources.reduce((total, resource) => total + (resource.downloadBytes ?? 0), 0), estimated = groupResources.some(resource => resource.sizeEstimated || resource.downloadBytes === undefined); return `<section class="resource-group"><div class="resource-group-heading"><div><h3>${escapeHtml(group)}</h3><span class="resource-group-size">${estimated ? "Estimated " : ""}${formatBytes(groupBytes)} total</span></div><button class="download-group" type="button" data-resource-group="${escapeHtml(group)}" ${downloadLocked || groupReady || resourceDownloadActive ? "disabled" : ""} title="${downloadLocked ? "Hardware compatibility check required" : groupReady ? "All resources in this group are installed" : "Download all missing resources in this group"}">Download All</button></div>${groupResources.map(resource => `<article class="resource-item"><div class="resource-copy"><div><strong>${escapeHtml(resource.name)}</strong><span class="resource-status ${resource.available ? "installed" : "missing"}">${resource.available ? "Installed" : "Missing"}</span>${resource.optional ? '<span class="optional-label">Optional</span>' : ""}</div><p>${escapeHtml(resource.description)}</p><code title="${escapeHtml(resource.path)}">${escapeHtml(resource.path)}</code></div><div class="resource-side"><span class="resource-size">${resource.sizeEstimated ? "~" : ""}${resource.downloadBytes === undefined ? "Size unknown" : formatBytes(resource.downloadBytes)}</span><button class="download-resource" type="button" data-resource-id="${escapeHtml(resource.id)}" ${downloadLocked || resource.available || resourceDownloadActive ? "disabled" : ""} title="${downloadLocked ? "Hardware compatibility check required" : resource.available ? "This resource is installed" : `Download ${escapeHtml(resource.name)}`}">${resourceDownloadActive ? "Please wait" : "Download"}</button></div></article>`).join("")}</section>`; }).join("");
  $("#resources-list").querySelectorAll<HTMLButtonElement>(".download-group:not(:disabled)").forEach(button => { button.onclick = () => downloadResources(runtimeResources.filter(resource => resource.group === button.dataset.resourceGroup && !resource.available).map(resource => resource.id)); });
  $("#resources-list").querySelectorAll<HTMLButtonElement>(".download-resource:not(:disabled)").forEach(button => { button.onclick = () => downloadResources([button.dataset.resourceId!]); });
}
async function downloadResources(ids: string[]): Promise<void> {
  if (!downloadHardwareApproved) { $("#resources-modal").hidden = true; await scanHardware(); return; }
  if (resourceDownloadActive || !ids.length) return;
  resourceDownloadActive = true; $("#download-meter").hidden = false; $("#download-meter-fill").style.width = "0%"; renderResources();
  let failure = "";
  try {
    for (let index = 0; index < ids.length; index++) {
      const resource = runtimeResources.find(item => item.id === ids[index]);
      activeDownloadPosition = ` · resource ${index + 1}/${ids.length}`;
      $("#resources-summary-text").textContent = `Preparing ${resource?.name ?? ids[index]}${activeDownloadPosition}`;
      const result = await invoke<DownloadResult>("download_resource", { resourceId: ids[index] });
      $("#resources-summary-text").textContent = `Installed ${resource?.name ?? result.resourceId} · ${formatBytes(result.bytes)}`;
    }
  } catch (error) { failure = String(error); }
  finally {
    resourceDownloadActive = false; activeDownloadPosition = ""; await refreshResources();
    $("#download-meter").hidden = true; $("#download-meter").classList.remove("indeterminate");
    if (failure) $("#resources-summary-text").textContent = `Download paused: ${failure}. Click Download again to resume.`;
  }
}
async function refreshResources(): Promise<void> { const refresh = $<HTMLButtonElement>("#refresh-resources"); refresh.disabled = true; refresh.textContent = "Checking…"; try { const model = await invoke<RuntimeProbe>("probe_flux"); runtimeResources = model.resources ?? []; fluxAvailable = model.available; renderResources(); updateRuntimeState(); } catch { runtimeResources = []; fluxAvailable = false; renderResources(); updateRuntimeState(); } finally { refresh.disabled = false; refresh.textContent = "Refresh status"; } }
function setupResizer(selector: string, side: "left" | "right"): void { const handle = $(selector), workspace = $("#workspace"); handle.onpointerdown = event => { handle.setPointerCapture(event.pointerId); document.body.classList.add("resizing-panels"); }; handle.onpointermove = event => { if (!handle.hasPointerCapture(event.pointerId)) return; const rect = workspace.getBoundingClientRect(), value = side === "left" ? event.clientX - rect.left : rect.right - event.clientX, clamped = Math.round(Math.max(side === "left" ? 180 : 300, Math.min(side === "left" ? 460 : 620, value))); if (side === "left") settings.leftPanelWidth = clamped; else settings.rightPanelWidth = clamped; workspace.style.setProperty(side === "left" ? "--left-width" : "--right-width", `${clamped}px`); }; handle.onpointerup = event => { if (handle.hasPointerCapture(event.pointerId)) handle.releasePointerCapture(event.pointerId); document.body.classList.remove("resizing-panels"); persist(); }; }

$("#choose-source").onclick = async () => { const value = await open({ directory: true, multiple: false, title: "Choose source asset root" }); if (typeof value === "string") await scanInput(value); };
$("#choose-output").onclick = async () => { const value = await open({ directory: true, multiple: false, title: "Choose mirrored output root" }); if (typeof value === "string") { settings.outputRoot = value; $("#output-path").textContent = value; persist(); await scanOutput(true); } };
$("#dry-run").onclick = () => scanInput(); $("#input-tab").onclick = () => { activeView = "input"; currentDir = ""; renderAll(); }; $("#output-tab").onclick = async () => { activeView = "output"; currentDir = ""; await scanOutput(); }; $("#search").oninput = renderAll; $("#status-filter").onchange = renderAll; $<HTMLSelectElement>("#group-by").onchange = () => { persist(); renderAssets(); };
$("#grid-view").onclick = () => { settings.view = "grid"; $("#grid-view").classList.add("active"); $("#list-view").classList.remove("active"); persist(); renderAssets(); }; $("#list-view").onclick = () => { settings.view = "list"; $("#list-view").classList.add("active"); $("#grid-view").classList.remove("active"); persist(); renderAssets(); };
$("#select-visible").onchange = event => { const checked = (event.target as HTMLInputElement).checked; for (const asset of visibleAssets()) { if (checked) { selected.add(asset.relativePath); if (!queue.has(asset.relativePath)) queue.set(asset.relativePath, "queued"); } else { selected.delete(asset.relativePath); queue.delete(asset.relativePath); } } renderAll(); }; $("#clear-selection").onclick = () => { selected.clear(); queue.clear(); renderAll(); }; $("#clear-queue").onclick = () => { selected.clear(); queue.clear(); results.clear(); renderAll(); };
$("#add-color").onclick = addColor; $("#lora-enabled").onchange = () => { updateRuntimeState(); persist(); }; $("#lora-strength").oninput = () => { $("#lora-strength-value").textContent = Number($<HTMLInputElement>("#lora-strength").value).toFixed(2); persist(); }; $("#denoise-strength").oninput = () => { $("#denoise-strength-value").textContent = Number($<HTMLInputElement>("#denoise-strength").value).toFixed(2); persist(); }; $("#structure-preservation").oninput = () => { $("#structure-preservation-value").textContent = Number($<HTMLInputElement>("#structure-preservation").value).toFixed(2); persist(); }; $<HTMLSelectElement>("#inference-steps").onchange = persist; $("#style-lock-enabled").onchange = persist; $("#style-seed").onchange = persist; $("#seed-decrement").onclick = () => setSeed(Number($<HTMLInputElement>("#style-seed").value) - 1); $("#seed-increment").onclick = () => setSeed(Number($<HTMLInputElement>("#style-seed").value) + 1); $("#randomize-seed").onclick = () => setSeed(crypto.getRandomValues(new Uint32Array(1))[0]);
$<HTMLSelectElement>("#working-resolution").onchange = updateResolutionNote; $<HTMLInputElement>("#minimum-resolution-enabled").onchange = updateResolutionNote; $<HTMLInputElement>("#content-aware-scaling").onchange = persist; ["#style-prompt", "#overwrite"].forEach(id => $(id).addEventListener("input", persist));
$("#run-batch").onclick = async () => { persist(); const issue = runtimeIssue(); if (issue) { runtimeBlockingMessage = issue; setStatus(issue, "failed"); openResourcesModal(); return; } if (!inventory || !settings.outputRoot) { setStatus("Choose source and output folders first.", "failed"); return; } const entries = [...queue].filter(([, state]) => state === "queued" || state === "complete"), paths = entries.map(([path]) => path), repaintingCompleted = entries.some(([, state]) => state === "complete"); if (!paths.length) { setStatus("Check at least one input image.", "failed"); return; } paths.forEach(path => queue.set(path, "processing")); renderAll(); setStatus(`FLUX running · ${paths.length} assets`, "running"); try { const request = { sourceRoot: inventory.root, outputRoot: settings.outputRoot, relativePaths: paths, stylePrompt: settings.stylePrompt, palette: palettePrompt(), loraEnabled: settings.loraEnabled, loraStrength: settings.loraStrength, denoisingStrength: settings.fluxDenoisingStrength, structurePreservation: settings.structurePreservation, inferenceSteps: settings.inferenceSteps, overwrite: settings.overwrite || repaintingCompleted, styleLockEnabled: settings.styleLockEnabled, styleSeed: settings.styleSeed, styleFingerprint: styleFingerprint(), workingResolution: settings.workingResolution, minimumResolutionEnabled: settings.minimumResolutionEnabled, contentAwareScaling: settings.contentAwareScaling }; const response = await invoke<ProcessResult[]>("run_flux_batch", { request }); response.forEach(result => { const cached = blobUrls.get(result.outputPath); if (cached) { URL.revokeObjectURL(cached); blobUrls.delete(result.outputPath); } results.set(result.relativePath, result); queue.set(result.relativePath, result.status); }); await scanOutput(true); renderAll(); setStatus(`Batch complete · ${response.filter(value => value.valid).length}/${response.length} validated`, "complete"); } catch (error) { paths.forEach(path => queue.set(path, "failed")); renderAll(); setStatus(`Batch failed: ${String(error)}`, "failed"); } };
$("#preview").onclick = event => { if ((event.target as HTMLElement).id === "preview" || (event.target as HTMLElement).classList.contains("preview-stage")) closePreview(); };
$("#close-comparison").onclick = () => $("#comparison").hidden = true; $("#comparison").onclick = event => { if ((event.target as HTMLElement).id === "comparison") $("#comparison").hidden = true; };
$("#open-resources").onclick = openResourcesModal;
$("#close-preflight").onclick = () => $("#preflight-modal").hidden = true;
$("#preflight-modal").onclick = event => { if ((event.target as HTMLElement).id === "preflight-modal") $("#preflight-modal").hidden = true; };
$("#rescan-system").onclick = () => void scanHardware();
$("#continue-downloads").onclick = () => { if (!downloadHardwareApproved) return; $("#preflight-modal").hidden = true; showResourcesModal(); };
$("#close-resources").onclick = () => $("#resources-modal").hidden = true;
$("#resources-modal").onclick = event => { if ((event.target as HTMLElement).id === "resources-modal") $("#resources-modal").hidden = true; };
$("#refresh-resources").onclick = refreshResources;
$("#close-color-picker").onclick = closeColorPicker; $<HTMLInputElement>("#color-value").oninput = event => { pickerValue = Number((event.target as HTMLInputElement).value); applyPickerColor(); }; $<HTMLInputElement>("#color-hex").onchange = event => { const hex = normalizeHex((event.target as HTMLInputElement).value); if (!hex || paletteEditingIndex === null) { (event.target as HTMLInputElement).value = paletteEditingIndex === null ? "" : settings.paletteColors[paletteEditingIndex].hex; return; } settings.paletteColors[paletteEditingIndex].hex = hex; [pickerHue, pickerSaturation, pickerValue] = rgbToHsv(...hexToRgb(hex)); $<HTMLInputElement>("#color-value").value = String(pickerValue); applyPickerColor(); };
const colorWheel = $<HTMLCanvasElement>("#color-wheel"), pickWheel = (event: PointerEvent) => { const rect = colorWheel.getBoundingClientRect(), radius = rect.width / 2, dx = event.clientX - rect.left - radius, dy = event.clientY - rect.top - radius; pickerSaturation = Math.min(1, Math.sqrt(dx * dx + dy * dy) / (radius - 3)); pickerHue = (Math.atan2(dy, dx) * 180 / Math.PI + 360) % 360; applyPickerColor(); }; colorWheel.onpointerdown = event => { colorWheel.setPointerCapture(event.pointerId); pickWheel(event); }; colorWheel.onpointermove = event => { if (colorWheel.hasPointerCapture(event.pointerId)) pickWheel(event); }; colorWheel.onpointerup = event => { if (colorWheel.hasPointerCapture(event.pointerId)) colorWheel.releasePointerCapture(event.pointerId); };
document.addEventListener("mouseover", event => { const tip = (event.target as HTMLElement).closest<HTMLElement>(".help-tip"); if (tip) showTooltip(tip); });
document.addEventListener("mouseout", event => { const tip = (event.target as HTMLElement).closest<HTMLElement>(".help-tip"); if (tip && !(event.relatedTarget as HTMLElement | null)?.closest?.(".help-tip")) hideTooltip(); });
document.addEventListener("focusin", event => { const tip = (event.target as HTMLElement).closest<HTMLElement>(".help-tip"); if (tip) showTooltip(tip); });
document.addEventListener("focusout", event => { if ((event.target as HTMLElement).closest(".help-tip")) hideTooltip(); });
document.addEventListener("scroll", hideTooltip, true); window.addEventListener("resize", hideTooltip);
window.addEventListener("pagehide", persist);
window.addEventListener("beforeunload", persist);

$("#source-path").textContent = settings.sourceRoot || "Not selected"; $("#output-path").textContent = settings.outputRoot || "Not selected"; $<HTMLTextAreaElement>("#style-prompt").value = settings.stylePrompt; $<HTMLInputElement>("#lora-enabled").checked = settings.loraEnabled; $<HTMLInputElement>("#lora-strength").value = String(settings.loraStrength); $("#lora-strength-value").textContent = settings.loraStrength.toFixed(2); $<HTMLInputElement>("#overwrite").checked = settings.overwrite; $<HTMLSelectElement>("#group-by").value = settings.groupBy; $<HTMLInputElement>("#style-lock-enabled").checked = settings.styleLockEnabled; $<HTMLInputElement>("#style-seed").value = String(settings.styleSeed); $<HTMLSelectElement>("#working-resolution").value = String(settings.workingResolution); $<HTMLInputElement>("#minimum-resolution-enabled").checked = settings.minimumResolutionEnabled; $<HTMLInputElement>("#content-aware-scaling").checked = settings.contentAwareScaling; $<HTMLInputElement>("#denoise-strength").value = String(settings.fluxDenoisingStrength); $("#denoise-strength-value").textContent = settings.fluxDenoisingStrength.toFixed(2); $<HTMLInputElement>("#structure-preservation").value = String(settings.structurePreservation); $("#structure-preservation-value").textContent = settings.structurePreservation.toFixed(2); $<HTMLSelectElement>("#inference-steps").value = String(settings.inferenceSteps);
const workspace = $("#workspace"); workspace.style.setProperty("--left-width", `${settings.leftPanelWidth}px`); workspace.style.setProperty("--right-width", `${settings.rightPanelWidth}px`); setupResizer("#left-resizer", "left"); setupResizer("#right-resizer", "right"); renderPalette(); updateResolutionNote(); updateRuntimeState(); renderStyleFingerprint(); if (settings.view === "list") { $("#list-view").classList.add("active"); $("#grid-view").classList.remove("active"); }
refreshResources();
if (settings.sourceRoot) scanInput(); else renderAll();
